### ISSUE TITLE
Build crashing when decal projector is used in any scene.

### ISSUE THREAD

**Issue by CodeOstrich9900** [EricFreeman/DynamicDecals#5]
I'm using 2022.3.32f1 .  The build crashes when there is a projector component in scene.

**Comment by EricFreeman** [comment]
Any console errors or anything in the editor logs?

**Comment by CodeOstrich9900** [comment]
Subject: Issue with Decal Tool in Build - Editor Logs Not Available



Thank you for your response. Unfortunately, I’ve already removed the tool
from my project, so I no longer have access to the editor logs. However, I
do recall seeing several warnings in the Unity Editor related to deprecated
features (I believe that was the term used). The warnings mentioned that
certain methods or components were deprecated and suggested using
alternatives instead.

These warnings were persistent, and I suspect they might have contributed
to the crash I experienced after the "Made with Unity" screen in the build
when using the decal projector in the scene.

I no longer have the tool in my project, but if needed, I can reinstall and
check the logs again.

Thanks for your time, and I look forward to your advice!

**Comment by HunterAhlquist** [comment]
I'm having the same problem in Unity 6000.3.9.
It only appears in the Vulkan renderer (Have not tested DirectX, and the Metal renderer has no issue), and my Player.log doesn't indicate anything specific... this was the last thing:
```
Missing Vulkan framebuffer attachment image?
Received signal SIGSEGV (11) - code:1 errno:0 addr:0xc8
Obtained 14 stack frames.
#0  0x007f9d5b44bd10 in (Unknown)
#1  0x007f9c7437cfb6 in (Unknown)
#2  0x007f9c742a610d in (Unknown)
#3  0x007f9d5cd6e486 in (Unknown)
#4  0x007f9d5cd9a49d in (Unknown)
#5  0x007f9d5cd9aac6 in (Unknown)
#6  0x007f9d5cdc8eb6 in (Unknown)
#7  0x007f9d5cde9279 in (Unknown)
#8  0x007f9d5d8046f8 in (Unknown)
#9  0x007f9d5d7fd4f3 in (Unknown)
#10 0x007f9d5d8077f0 in (Unknown)
#11 0x007f9d5d6ad893 in (Unknown)
#12 0x007f9d5b4a3688 in (Unknown)
#13 0x007f9d5b52796c in (Unknown)
```

**Comment by HunterAhlquist** [comment]
Tested DX11 via Proton, works just fine. Also tested Vulkan via Proton on Steam Deck, same kind of crash. 
Seems to be an issue with Vulkan exclusively.

**Comment by HunterAhlquist** [comment]
Running the editor in Linux, which uses Vulkan, as soon as I loaded a scene that uses decals it crashes. Here is the long, I feel like this is far beyond my skill level. 

[Editor.log](https://github.com/user-attachments/files/25806979/Editor.log)
